import { NextResponse } from "next/server";
import { createSessionToken } from "@/lib/auth";
import {
  buildAppSessionFromSupabaseUser,
  getRequestOrigin,
  resolveProfileForUser,
} from "@/lib/supabase-auth";
import { supabaseAdmin } from "@/lib/supabase-admin";

function getSafeRedirectPath(value) {
  const raw = String(value || "").trim();
  if (!raw.startsWith("/")) return "/dashboard";
  if (raw.startsWith("//")) return "/dashboard";
  if (raw.startsWith("/auth/")) return "/dashboard";
  return raw;
}

import { verifyEmailConfirmToken } from "@/lib/auth";

const AUTH_DEBUG = process.env.NEXT_PUBLIC_AUTH_DEBUG === "1";

function maskToken(value) {
  const raw = String(value || "");
  if (!raw) return null;
  if (raw.length <= 12) return `${raw.slice(0, 2)}***${raw.slice(-2)}`;
  return `${raw.slice(0, 6)}...${raw.slice(-6)}`;
}

function getIncomingCookieNames(request) {
  return request.cookies.getAll().map((cookie) => cookie.name);
}

const SESSION_COOKIE_NAME =
  process.env.NODE_ENV === "production"
    ? "__Host-madrid_session"
    : "madrid_session";

const SESSION_COOKIE_MAX_AGE = Number(
  process.env.SESSION_TTL_SECONDS || 60 * 60 * 24 * 7,
);

function setSessionOnRedirect(target, sessionToken) {
  const response = NextResponse.redirect(target);
  response.cookies.set(SESSION_COOKIE_NAME, sessionToken, {
    path: "/",
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    maxAge: SESSION_COOKIE_MAX_AGE,
  });
  return response;
}

export async function GET(request) {
  const url = new URL(request.url);
  const vt = String(url.searchParams.get("vt") || "").trim();
  const authError = String(url.searchParams.get("error") || "").trim();
  const origin = getRequestOrigin(request) || url.origin;
  const target = new URL(getSafeRedirectPath(url.searchParams.get("next")), origin);

  if (AUTH_DEBUG) {
    console.info("[auth/callback] entry", {
      pathname: url.pathname,
      search: url.search,
      hasVt: Boolean(vt),
      hasCode: Boolean(url.searchParams.get("code")),
      hasTokenHash: Boolean(url.searchParams.get("token_hash")),
      hasAccessToken: Boolean(url.searchParams.get("access_token")),
      hasRefreshToken: Boolean(url.searchParams.get("refresh_token")),
      authError,
      incomingCookies: getIncomingCookieNames(request),
      redirectDestination: target.pathname,
    });
  }

  if (authError) {
    return NextResponse.redirect(
      new URL(`/verify-email?auth_error=${encodeURIComponent(authError)}`, origin),
    );
  }

  // ── PRIMARY PATH: our signed verification token ───────────────────────────
  // Generated by createEmailConfirmToken(userId, email) — verified here with
  // our SESSION_SECRET. Bypasses all verifyOtp / SSR cookie complexity.
  if (vt) {
    const verified = verifyEmailConfirmToken(vt);
    if (!verified?.userId) {
      console.error("[auth/callback] invalid or expired vt token");
      return NextResponse.redirect(
        new URL("/verify-email?auth_error=expired_token", origin),
      );
    }

    const { data: userData, error: getUserError } =
      await supabaseAdmin.auth.admin.getUserById(verified.userId);

    if (getUserError || !userData?.user) {
      console.error("[auth/callback] user not found for vt", { error: getUserError?.message });
      return NextResponse.redirect(
        new URL("/verify-email?auth_error=exchange_failed", origin),
      );
    }

    let user = userData.user;

    if (!user.email_confirmed_at) {
      const now = new Date().toISOString();
      const trialEnd = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
      const { error: confirmError } = await supabaseAdmin.auth.admin.updateUserById(
        user.id,
        {
          email_confirm: true,
          user_metadata: {
            ...user.user_metadata,
            status: "active",
            trialStartDate: user.user_metadata?.trialStartDate || now,
            trialEndDate: user.user_metadata?.trialEndDate || trialEnd,
          },
        },
      );
      if (confirmError) {
        console.error("[auth/callback] email confirm failed", { error: confirmError.message });
        return NextResponse.redirect(
          new URL("/verify-email?auth_error=exchange_failed", origin),
        );
      }
      // Re-fetch to get updated email_confirmed_at
      const { data: fresh } = await supabaseAdmin.auth.admin.getUserById(user.id);
      user = fresh?.user || user;
    } else {
      // Already confirmed — fix status if stuck
      const status = String(user.user_metadata?.status || "");
      if (!status || status === "pending_verification") {
        const now = new Date().toISOString();
        const trialEnd = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
        supabaseAdmin.auth.admin.updateUserById(user.id, {
          user_metadata: {
            ...user.user_metadata,
            status: "active",
            trialStartDate: user.user_metadata?.trialStartDate || now,
            trialEndDate: user.user_metadata?.trialEndDate || trialEnd,
          },
        }).then(({ error: e }) => {
          if (e) console.warn("[auth/callback] status fix failed", e.message);
        });
      }
    }

    const profile = await resolveProfileForUser(user, {
      tenantId: user.id,
      role: user.app_metadata?.role,
    });
    const sessionToken = createSessionToken(
      buildAppSessionFromSupabaseUser(user, null, profile),
    );

    if (AUTH_DEBUG) {
      console.info("[auth/callback] session created via vt", {
        userId: user.id,
        accessToken: null,
        refreshToken: null,
        redirectDestination: target.pathname,
        setCookieName: SESSION_COOKIE_NAME,
        sessionTokenHint: maskToken(sessionToken),
      });
    }
    return setSessionOnRedirect(target, sessionToken);
  }

  // ── LEGACY PATH: Supabase token_hash / code / access_token ────────────────
  const code = String(url.searchParams.get("code") || "").trim();
  const tokenHash = String(url.searchParams.get("token_hash") || "").trim();
  const otpType = String(url.searchParams.get("type") || "").trim();
  const accessToken = String(url.searchParams.get("access_token") || "").trim();
  const refreshToken = String(url.searchParams.get("refresh_token") || "").trim();

  if (!code && !tokenHash && !accessToken) {
    return NextResponse.redirect(new URL("/verify-email?auth_error=missing_code", origin));
  }

  const { createSupabaseServerAuthClient } = await import("@/lib/supabase-auth");
  const supabase = createSupabaseServerAuthClient();
  let exchangeData = null;
  let exchangeError = null;

  if (code) {
    ({ data: exchangeData, error: exchangeError } = await supabase.auth.exchangeCodeForSession(code));
    if (AUTH_DEBUG) {
      console.info("[auth/callback] exchangeCodeForSession", {
        hasSession: Boolean(exchangeData?.session),
        hasUser: Boolean(exchangeData?.user),
        error: exchangeError?.message || null,
        accessToken: maskToken(exchangeData?.session?.access_token),
        refreshToken: maskToken(exchangeData?.session?.refresh_token),
      });
    }
  } else if (tokenHash) {
    const types = otpType
      ? [otpType, "signup", "email", "magiclink"].filter((v, i, a) => a.indexOf(v) === i)
      : ["signup", "email", "magiclink"];
    for (const t of types) {
      ({ data: exchangeData, error: exchangeError } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: t }));
      if (AUTH_DEBUG) {
        console.info("[auth/callback] verifyOtp", {
          candidateType: t,
          hasSession: Boolean(exchangeData?.session),
          hasUser: Boolean(exchangeData?.user),
          error: exchangeError?.message || null,
          accessToken: maskToken(exchangeData?.session?.access_token),
          refreshToken: maskToken(exchangeData?.session?.refresh_token),
        });
      }
      if (!exchangeError && exchangeData?.user) break;
    }
  } else if (accessToken && refreshToken) {
    const r = await supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken });
    exchangeData = { session: r.data?.session, user: r.data?.user || r.data?.session?.user };
    exchangeError = r.error;
    if (AUTH_DEBUG) {
      console.info("[auth/callback] setSession fallback", {
        hasSession: Boolean(exchangeData?.session),
        hasUser: Boolean(exchangeData?.user),
        error: exchangeError?.message || null,
        accessToken: maskToken(exchangeData?.session?.access_token),
        refreshToken: maskToken(exchangeData?.session?.refresh_token),
      });
    }
  }

  if (exchangeError || !exchangeData?.user) {
    console.error("[auth/callback] legacy exchange failed", { error: exchangeError?.message });
    return NextResponse.redirect(new URL("/verify-email?auth_error=exchange_failed", origin));
  }

  const user = exchangeData.user;
  if (!user.email_confirmed_at) {
    return NextResponse.redirect(new URL("/verify-email?auth_error=email_not_confirmed", origin));
  }

  // Fix status if needed
  const status = String(user.user_metadata?.status || "");
  if (!status || status === "pending_verification") {
    const now = new Date().toISOString();
    const trialEnd = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
    supabaseAdmin.auth.admin.updateUserById(user.id, {
      user_metadata: { ...user.user_metadata, status: "active",
        trialStartDate: user.user_metadata?.trialStartDate || now,
        trialEndDate: user.user_metadata?.trialEndDate || trialEnd },
    }).then(({ error: e }) => { if (e) console.warn("[auth/callback] status fix failed", e.message); });
  }

  const profile = await resolveProfileForUser(user, {
    tenantId: user.id,
    role: user.app_metadata?.role,
  });
  const sessionToken = createSessionToken(
    buildAppSessionFromSupabaseUser(user, exchangeData.session, profile),
  );
  if (AUTH_DEBUG) {
    console.info("[auth/callback] session created via legacy exchange", {
      userId: user.id,
      accessToken: maskToken(exchangeData?.session?.access_token),
      refreshToken: maskToken(exchangeData?.session?.refresh_token),
      redirectDestination: target.pathname,
      setCookieName: SESSION_COOKIE_NAME,
      sessionTokenHint: maskToken(sessionToken),
    });
  }
  return setSessionOnRedirect(target, sessionToken);
}
